import Head from 'next/head'
import Header from '@/componentes/Header'
import SubHeader from '@/componentes/SubHeader'
import Section from '@/componentes/Section'
export default function Home() {
  return (
    <>
      <Head>
        <title>Barber Shop App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <SubHeader/>
      <Section/>
    </>
  )
}
